name: Update manifest

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: write

jobs:
  update:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        
      - name: Checkout Scoop
        run: git clone https://github.com/ScoopInstaller/Scoop.git

      - name: Run checkver on manifest
        run: pwsh ./Scoop/bin/checkver.ps1 "$PWD/bucket/cryptomator.json" -Update

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add bucket/cryptomator.json
          git commit -m "Update manifest" || echo "No changes to commit"
          git push
